# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/trusty64"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network "forwarded_port", guest: 5601, host: 8080
  config.vm.network "forwarded_port", guest: 9200, host: 9200

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder "logstash", "/etc/logstash/conf.d"

  # #
  # config.vm.provider "vmware_fusion" do |vmwf, override|
  #   #override.vm.box_url = "http://files.vagrantup.com/precise64_vmware.box"
  #   vmwf.gui = false
  #   vmwf.vmx["displayName"] = "ELK"
  #   vmwf.vmx["numvcpus"] = "4"
  #   vmwf.vmx["memsize"] = "4096"
  # end

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
    vb.name = "ELK"
    # Customize the amount of memory on the VM:
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
    vb.cpus = 4
    vb.memory = "4096"
  end

  config.vm.provision "shell", path: "setup/install_java8.sh"
  config.vm.provision "shell", path: "setup/install_elk.sh"
  config.vm.provision "shell", path: "setup/install_prezto.sh"
  config.vm.provision "shell", path: "setup/install_bro.sh"
end
